export { default as Home } from './Home'
export { default as Setting } from './Setting'
export { default as Reward } from './Reward'
export { default as Event } from './Event'
export { default as Play } from './Play'
